version: 0.2

phases:

  pre_build:

    commands:

      - "echo Logging in to Docker Hub..."


  build:

    commands:

      - "echo Build started on `date`"

      - "echo Building the Docker image..."

      - "docker build -t laumcaicedo/APPDemoGVE:latest ."

      - "docker tag dlaumcaicedo/APPDemoGVE:latest laumcaicedo/APPDemoGVE:latest"

  post_build:

    commands:

      - "echo Build completed on `date`"

      - "echo Pushing the Docker image..."

      - "docker push laumcaicedo/APPDemoGVE:latest"

 
