version: 0.2

phases:

  pre_build:

    commands:

      - "echo Logging in to Docker Hub..."

      - "docker login --username=\"laumcaicedo\" --password=\"passw0rd\""

  build:

    commands:

      - "echo Build started on `date`"

      - "echo Building the Docker image..."

      - "docker build -t laumcaicedo/Repo:latest ."

      - "docker tag dlaumcaicedo/Repo:latest laumcaicedo/Repo:latest"

  post_build:

    commands:

      - "echo Build completed on `date`"

      - "echo Pushing the Docker image..."

      - "docker push laumcaicedo/Repo:latest"

 
